### ISSUE TITLE
The example works, except you may need to update the URL scheme in Target.

### ISSUE THREAD

**Issue by higracehuang** [paraches/GoogleSignIn6_SwiftUI#1]
Otherwise, it will throw an exception, as described in https://stackoverflow.com/questions/42197729/app-getting-crash-when-click-on-googlesignin-button-why

**Comment by paraches** [comment]
Thank you for your message.
About URL scheme, it was written in Web page in README/Note. But its link was broken.
So I fix the link and now you can read it.
